services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Server=sqlserver,1433;Database=AuditDb;User Id=sa;Password=Your_strong_Passw0rd!;TrustServerCertificate=True;Encrypt=False

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: observability-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_strong_Passw0rd!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: observability-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:11.2.0
    container_name: observability-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana

volumes:
  sqlserver_data:
  grafana_data:
